Spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    httpClient:
      connect-timeout: 1000
      response-timeout: 5s
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000ms"

management:
  endpoints:
     web:
       exposure:
         include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Gateway Server for the application"
    version: "1.0.0"

resilience4j.circuitbreaker:
  config:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

